#!/usr/bin/env bash
# user id dir


# Check if /etc/passwd exists
if [ ! -f /etc/passwd ]; then
  echo "Error: /etc/passwd not found."
  exit 1
fi



while IFS=: read -r username _ uid _ _ home_dir _; do
  echo "$username:$uid:$home_dir"
done < /etc/passwd
