#!/usr/bin/env bash
# List filenames showing only the part after the first dash

for file in *; do
	
	[ -e "$file" ] || continue

	if [[ "$file" == *-* ]]; then 
		echo "${file#*-}"
	else 
		echo "$file"
	fi
done 
