#!/usr/bin/env bash
#comment
# shellcheck disable=SC2009

pid=$(pgrep -f 4-to_infinity_and_beyond)

if [ -z "$pid" ]; then
  echo "No 4-to_infinity_and_beyond process found."
  exit 1
fi

kill "$pid"
echo "Stopped process $pid"

