#!/usr/bin/env bash
#comment

# Trap SIGTERM and print a message before exiting
trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done

